# GitHub Funding / Sponsoring

# GitHub Sponsors
github: [Mosei1984]

# Optional: Weitere Plattformen
# ko_fi: username
# custom: ["https://www.buymeacoffee.com/username", "https://www.paypal.me/username"]
